### ISSUE TITLE
Support for mtl 2.2?

### ISSUE THREAD

**Issue by peti** [MichaelXavier/cron#15]
Would it be possible to get a version of this package that supports recent releases of `mtl`: http://packdeps.haskellers.com/feed?needle=cron-compat? Maybe 
http://hackage.haskell.org/package/mtl-compat can help achieve that?

**Comment by MichaelXavier** [comment]
I'm confused. Did you mean to post this on the cron-compat repo? We're trying to figure out how to satisfy both camps on issue #14 if you care to weigh in.

**Comment by peti** [comment]
I followed the links from Hackage trying to find the appropriate bug tracker. My apologies, if ended up in the wrong place. Anyway, as I said, I would use mtl-compat to support *all* versions of mtl.

**Comment by peti** [comment]
@MichaelXavier, where *is* the cron-compat repo? The Hackage page http://hackage.haskell.org/package/cron-compat links to this place in, "homepage", "issues", and "source repository".
