### ISSUE TITLE
Failure to parse a schedule line should throw an exception

### ISSUE THREAD

**Issue by andrewthad** [MichaelXavier/cron#17]
In a web app I'm building, I have the following lines with crontab entries that do not parse correctly:

    -- Somwhere far far away in an IO monad
    _ <- execSchedule $ do
      addJob (heartbeat app)                       "*   *   *   *   *"
      addJob (pushCalendarUpdatesToOffice365 app)  "*/5 *   *   *   *"
    pushLogStr (loggerSet $ appLogger app) $ "All cronjobs have been scheduled"

For some reason (that I'm still looking into), these don't parse correctly. However, my concern is not just about the failure to parse but about what happens after a failure. I see the following stdout when I run this:
    
    ParseError "Failed reading: takeWhile1"
    All cronjobs have been scheduled
    
So, `execSchedule` doesn't throw an exception in IO when something goes wrong, and I think that it would be better behavior if it did. This would make it more likely that people (cough cough... me) would discover mistakes at load time. Let me know what you think of this.

**Comment by MichaelXavier** [comment]
How would you feel about `execSchedule :: Schedule () -> IO Either ScheduleError [ThreadId]`? I agree that just printing is pretty shitty. Nothing can be done about it and having a bug in your scheduler just means the work doesn't get done, which is something that annoys me to no end about that actual cron. Still, because parse errors can all be confined to one type, I'm tempted to put it in the type system rather than throwing. I cold be convinced otherwise though.

**Comment by andrewthad** [comment]
I'm not at all opposed to `execSchedule :: Schedule () -> IO (Either ScheduleError [ThreadId])`. If the function does end up that way, then I can still propagate the exception to IO myself. However, I do think that throwing the exception is what the large majority of users would be interested in, so it would be nice to still support that out of the box. How about this:

    execScheduleEither :: Schedule () -> IO (Either ScheduleError [ThreadId])
    execSchedule :: Schedule () -> IO [ThreadId]

The idea is that `execSchedule` would basically be a convenience wrapper around `execScheduleEither`. This makes it easy to do what people usually want, and your API would stay backwards-compatible. You also wouldn't need the update the example at the top of the haddocks. Let me know what you think.

**Comment by MichaelXavier** [comment]
Fair enough. I think I'll just go with an exception. I wish to live in a world without them but I can see why for practical purposes, it can be the best choice for the end user, which should be the guiding force here.

**Comment by andrewthad** [comment]
Yeah, when I deal with functions whose inputs aren't known until the program is already running, I try to avoid exceptions in IO. But, if the value is known at load time, then I just end up converting everything to an IO exception. Since the scheduling of cron jobs is basically always known at load time, I think that the exception is, in this case, the best behavior.
