### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by Sir4ur0n** [MichaelXavier/cron#39]
Hi,

Thank you for this library, we currently use it in my team and it works like a charm :smile: 

I was wondering if this library is still maintained? Reasons why I ask:

* Build is failed on the badge (https://travis-ci.org/MichaelXavier/cron)
* Latest Hackage upload was on November 2017 while there were several commits since
* `cron` is not included in the next Stackage release (as is), I suspect because of the repeated build failures caused by `MonadFail` changes (which is a shame since I see a commit to fix this very issue in October 2019)

I hope this issue/question doesn't appear as rude :sweat_smile: I want to know if we need to fork it, or find an alternative (I did not find one yet), in anticipation of the next major GHC release 8.8 on Stack.

Cheers!

**Comment by MichaelXavier** [comment]
I think a fork is probably excessive considering the MonadFail instance is probably a really easy fix. To answer your question though, I consider this library pretty much "done" from what I set out to do, other than these occasional maintenance updates. If anyone wants to add features to it and they aren't extremely complex things I'll have to maintain, I'd gladly accept them.

Thank you for the nudge though. I'll try to find some time soon to hopefully quickly fix the MonadFail issue and cut a release.

**Comment by Sir4ur0n** [comment]
Thank you @MichaelXavier for the reply!
Indeed I am more than happy if you keep it building (and deployed 😄).
Let me know if I/we can help (on the building part; I highly doubt we can help on the publishing part).

Cheers!
