### ISSUE TITLE
Publish back on Hackage/Stackage

### ISSUE THREAD

**Issue by Sir4ur0n** [MichaelXavier/cron#40]
Current version is no longer available on Stackage nightly (thus high risk of not being available once GHC 8.8 lands there), it would be awesome to fix the build if need be then publish back please.

**Comment by MichaelXavier** [comment]
Now we [wait](https://github.com/commercialhaskell/stackage/pull/5060).

**Comment by MichaelXavier** [comment]
That MR was merged.

**Comment by Sir4ur0n** [comment]
Thank you @MichaelXavier , I really appreciate your effort! 🙏
