### ISSUE TITLE
Exposing System.Cron.Schedule.forkJob

### ISSUE THREAD

**Issue by igrep** [MichaelXavier/cron#43]
I know this package is just "data structure and parser" by definition, but found the scheduling feature is  useful.
So I want to reuse it for one of my applications which parses the schedule specification in a different format.
In such a use case, `addJob`, `runSchedule`, etc are unnecessary: calling `forkJob` directly with `Job`s parsed by the application is sufficient and more efficient.
Can you expose `System.Cron.Schedule.forkJob`?

**Comment by MichaelXavier** [comment]
That seems reasonable. I'm swamped, so I'll accept an MR if you want to go ahead and expose that.

**Comment by mauke** [comment]
I could really use this function, too.

I'd like to be able to write an alternative to `execSchedule` that doesn't just print errors to `stdout` and keep running. To do that, I need to be able to call `forkJob`.

**Comment by igrep** [comment]
Looks fixed by https://github.com/MichaelXavier/cron/commit/d9193309bd06b04607898212f9c477af4894c021
